### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by XuanZhangg** [muxamilian/city-gan#1]
Hi, I come across the following when running the code. I am wondering do you have any ideas about how to fix it?

**sys.version 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Namespace(arg='None', batchSize=128, beta1=0.5, classifyGenerated=False, cropSize=128, cuda=True, dataroot='dataset', dataset='gan-city', function='train', hack=True, imageSize=150, lr=0.0002, manualSeed=None, maxSamples=9223372036854775807, ndf=64, netD='', netG='', ngf=64, niter=1, nonConditional=False, numClasses=None, numSamples=8, nz=100, outf='output.png', workers=2)
Random Seed:  3526
Classes: {'amsterdam': 0, 'manhattan': 1, 'paris': 2, 'vienna': 3}
Hack: True
Non-conditional: False
sys.version 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Namespace(arg='None', batchSize=128, beta1=0.5, classifyGenerated=False, cropSize=128, cuda=True, dataroot='dataset', dataset='gan-city', function='train', hack=True, imageSize=150, lr=0.0002, manualSeed=None, maxSamples=9223372036854775807, ndf=64, netD='', netG='', ngf=64, niter=1, nonConditional=False, numClasses=None, numSamples=8, nz=100, outf='output.png', workers=2)
Random Seed:  6670
Classes: {'amsterdam': 0, 'manhattan': 1, 'paris': 2, 'vienna': 3}
Hack: True
Non-conditional: False
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "gan.py", line 379, in <module>
        function()exitcode = _main(fd)

  File "gan.py", line 146, in train
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\spawn.py", line 114, in _main
        for data in dataloader:prepare(preparation_data)

  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\spawn.py", line 225, in prepare
    return self._get_iterator()
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    run_name="__mp_main__")
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\runpy.py", line 263, in run_path
    w.start()
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\process.py", line 112, in start
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\runpy.py", line 96, in _run_module_code
    self._popen = self._Popen(self)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\context.py", line 223, in _Popen
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\runpy.py", line 85, in _run_code
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\context.py", line 322, in _Popen
    exec(code, run_globals)
  File "C:\Users\Xuan\Documents\GitHub\city-gan-master\gan.py", line 379, in <module>
        return Popen(process_obj)function()

  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
  File "C:\Users\Xuan\Documents\GitHub\city-gan-master\gan.py", line 146, in train
    for data in dataloader:
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\reduction.py", line 60, in dump
    return self._get_iterator()
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError:     [Errno 32] Broken pipereturn _MultiProcessingDataLoaderIter(self)

  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Xuan\anaconda3\envs\CSE586\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.**

**Comment by muxamilian** [comment]
Maybe it's because your Python version is too new? I would try to get all dependencies in Docker so that you can have the proper version of every software without causing conflicts on your computer.
